local KEYVAL = "f8"

local UI = _G.Ess and _G.Ess.UI
if not (UI and UI.Menu) then
    Loader.Printf("SpawnMenu: load Ess (dist/Ess.lua) first"); return
end

local menu = Ess.UI.Menu{ title = "Weapon Spawner by Ferdilanz", key = KEYVAL }
menu:category("Weapons", function(da)
    da:category("Pistols", function(db)
        db:entry("Pistol",            function(ctx) ctx:spawn("pistol", 2);         ctx:hint("SPAWNED") end)
        db:entry("Covert Pistol",     function(ctx) ctx:spawn("Covert Pistol", 2);         ctx:hint("SPAWNED") end)
        db:entry("Desert Eagle",      function(ctx) ctx:spawn("Pistol (silver)", 2);        ctx:hint("SPAWNED") end)
        db:entry("Blanco's Revolver", function(ctx) ctx:spawn("Hunting Pistol", 2);        ctx:hint("SPAWNED") end)
    end)
    da:category("Machine Pistols", function(dc)
        dc:entry("Micro Uzi",        function(ctx) ctx:spawn("Machine Pistol (Uzi)", 2);         ctx:hint("SPAWNED") end)
        dc:entry("TMP",              function(ctx) ctx:spawn("Machine Pistol (TMP)", 2);         ctx:hint("SPAWNED") end)
        dc:entry("MAC-10",           function(ctx) ctx:spawn("machine pistol", 2);        ctx:hint("SPAWNED") end)
        dc:entry("PDW (PP2000)",     function(ctx) ctx:spawn("Machine Pistol (PP2000)", 2);        ctx:hint("SPAWNED") end)
    end)
    da:category("Assault Rifles", function(dd)
        dd:entry("AKM",    function(ctx) ctx:spawn("assault rifle", 2);         ctx:hint("SPAWNED") end)
        dd:entry("AK-103", function(ctx) ctx:spawn("assault rifle (vz)", 2);         ctx:hint("SPAWNED") end)
        dd:entry("QBZ-95", function(ctx) ctx:spawn("Bullpup Rifle", 2);        ctx:hint("SPAWNED") end)
        dd:entry("XM8",    function(ctx) ctx:spawn("combat rifle", 2);        ctx:hint("SPAWNED") end)
        dd:entry("M4A1",   function(ctx) ctx:spawn("carbine", 2);         ctx:hint("SPAWNED") end)
    end)
    da:category("Automatic Rifles", function(de)
        de:entry("M249 SAW",     function(ctx) ctx:spawn("Light MG", 2);         ctx:hint("SPAWNED") end)
        de:entry("RPK",          function(ctx) ctx:spawn("Automatic Rifle", 2);         ctx:hint("SPAWNED") end)
        de:entry("QJY-88 LMG",   function(ctx) ctx:spawn("Automatic Rifle (Chinese)", 2);         ctx:hint("SPAWNED") end)
    end)
    da:category("SMGs", function(df)
        df:entry("CF-05", function(ctx) ctx:spawn("sMG", 2);         ctx:hint("SPAWNED") end)
        df:entry("MP5SD", function(ctx) ctx:spawn("Covert SMG", 2);         ctx:hint("SPAWNED") end)
    end)
    da:category("Sniper Rifles", function(dg)
        dg:entry("SVD",              function(ctx) ctx:spawn("Sniper Rifle (SVD)", 2);         ctx:hint("SPAWNED") end)
        dg:entry("QBU-88",           function(ctx) ctx:spawn("Sniper Rifle", 2);         ctx:hint("SPAWNED") end)
        dg:entry("Barrett M95 AMR",  function(ctx) ctx:spawn("Anti-Material Rifle", 2);         ctx:hint("SPAWNED") end)
        dg:entry("KSVK 12.7 AMR",    function(ctx) ctx:spawn("Anti-Material Rifle (KSVK)", 2);         ctx:hint("SPAWNED") end)
    end)
    da:entry("Shotgun", function(ctx) ctx:spawn("Shotgun",2); ctx:hint("SPAWNED") end)
    da:category("Heavy", function(dh)
        dh:entry("Anti-Tank Missile Launcher",   function(ctx) ctx:spawn("AT Rocket", 2);         ctx:hint("SPAWNED") end)
        dh:entry("Anti-Air Missile Launcher",    function(ctx) ctx:spawn("Stinger", 2);         ctx:hint("SPAWNED") end)
        dh:entry("RPG-7",                        function(ctx) ctx:spawn("RPG", 2);         ctx:hint("SPAWNED") end)
        dh:entry("Fuel-Air RPG",                 function(ctx) ctx:spawn("Fuel-Air RPG", 2);         ctx:hint("SPAWNED") end)
        dh:entry("Grenade Launcher",             function(ctx) ctx:spawn("Grenade Launcher", 2);         ctx:hint("SPAWNED") end)
        dh:entry("Grenade Launcher PEP",         function(ctx) ctx:spawn("Grenade Launcher PEP", 2);         ctx:hint("SPAWNED") end)
    end)
    da:category("Special", function(di)
        di:entry("Portable Minigun",             function(ctx) ctx:spawn("Minigun", 2);         ctx:hint("SPAWNED") end)
        di:entry("Portable Minigun 900rpm",      function(ctx) ctx:spawn("Minigun 900", 2);         ctx:hint("SPAWNED") end)
        di:entry("Portable Minigun 1800rpm",     function(ctx) ctx:spawn("minigun 1800", 2);         ctx:hint("SPAWNED") end)
        di:entry("Portable Autocannon 1000rpm",  function(ctx) ctx:spawn("minigun 1000", 2);         ctx:hint("SPAWNED") end)
        di:entry("Riot Gun (Gas Grenades)",      function(ctx) ctx:spawn("Riot Gun", 2);         ctx:hint("SPAWNED") end)
        di:entry("Coilgun",                      function(ctx) ctx:spawn("Coilgun", 2);         ctx:hint("SPAWNED") end)
        di:entry("Cheat RPG",                    function(ctx) ctx:spawn("Cheat RPG", 2);         ctx:hint("SPAWNED") end)
    end)
end)


menu:entry("Close Menu", function(ctx) ctx:close() end)

-- Flip the menu open/closed. (This file re-runs every time you press F9, so this line does the toggle.)
menu:toggle()